### ISSUE TITLE
Could item drop from special shrine and/or be of special tier/ drop from nemesis survivor.

### ISSUE THREAD

**Issue by benjdidj** [derslayr10/PlayerBotsItems#1]
I kind of wish that they the survivors didn't need an item to be called. especially that it kind of dillude red item pool. the mods great though.

What could be cool is if the items be special drop after fighting a nemesis survivor.

**Comment by derslayr10** [comment]
Allow me to address your concerns in parts, both to make it easier on me to give a complete answer as well as to help ensure the message is received clearly.

1) Could item drop from special shrine?

A: In short, no. I have no intention of learning how to create Unity assets and the code involved to not only create the shrine, but to also have it working in game. This is simply too much work for me, as I work over 40 hours a week on top of being a full time student in college. If you find this to be of something important to you, by all means feel free to play with my code and figure it out, that's why I posted the source code to start with.

2) Can item be of special tier?

A: The way that RoR2 handles tiers is much more than just saying what tier the items are. Currently, the tiers are Tier 1 (white), Tier 2 (green), Tier 3 (red), Tier Boss (I think this is what it is called, but am not certain, anyways it's the boss tier items, and Tier Lunar (lunar items). To create a new tier would be an immense amount of work that, due to the reasons I stated previously, I simply do not have time for. I placed the items in the Red Item tier because they are much more powerful than boss items, and really only fit with Red Items in my personal opinion.

3) Can item be special drop from nemesis survivor?

A: I will, for the sake of my sanity, assume that by "nemesis survivor", you mean the avatar that is spawned from the Artifact of Vengeance (aka the Umbras). If so, there is a way to make them drop from this, but I currently do not know how, nor do I intend to figure this out. If you do not mean the Umbra, and instead mean the Nemesis Enforcer from the Enforcer Mod, then that is something else entirely, and would be better asked of the Enforcer team to add a red item drop from defeating the Nemesis Enforcer, as I currently do not believe the boss drops any item.

4) I wish the survivors did not need the item to be called.

A: The answer to this is: They don't! All my mod does is add items that, on pickup, calls a method from the PlayerBots mod, which means anything to do with the bots comes from that mod (hence why it is a hard dependency and my mod will not work without it). That mod allows the survivors to be spawned via the in-game console, and has extra config options for customizing the bots. Be sure to check out the [PlayerBots mod on their Thunderstore page](https://thunderstore.io/package/Meledy/PlayerBots/) to find out more about how the bots work.

With all this being said, I am glad you are enjoying the mod, and feel free to let me know of any other issues or concerns you may have regarding the mod.

**Comment by benjdidj** [comment]
Thanks taking the time for this long answer.
1-2. I guessed that was complicated. You're right, keep the good work for your studies.
3  Thx for answering the question i had on this topic,(umbra and nemesis). I was wondering in the two cases , even if not stated.
4 I played with Player bots few months ago, thats why i checked your mod asap.
